driver:
  name: docker
  dns:
    - 8.8.8.8
    - 8.8.4.4
  image: kakakikikeke/ubuntu22-for-kitchen

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-22.04

suites:
  - name: default
    run_list:
      - recipe[cookbooks-emacs::default]
    attributes:
      owner: root
      group: root
      package:
        install: []
    verifier:
      name: shell
