; for some keybinds
(global-set-key "\C-\\" 'undo)
(global-unset-key "\C-h")
(global-set-key "\C-h" 'delete-backward-char)
(global-set-key "\M-g" 'goto-line)
(global-set-key "\M-s" 'replace-string)
(global-unset-key "\C-xh")
(global-set-key "\M-a" 'mark-whole-buffer)
(global-unset-key "\C-x3")
(global-set-key "\C-x5" 'split-window-horizontally)
(global-unset-key "\C-o")
(global-set-key "\C-o" 'other-window)
(global-unset-key "\C-]")
(global-set-key "\C-]" 'next-buffer)
(global-set-key "\C-c\C-x" 'eval-buffer)
(global-set-key (kbd "C-t") 'dabbrev-expand)
(define-key minibuffer-local-map (kbd "C-t") 'dabbrev-expand)
(global-set-key "\C-x;" 'helm-mini)
(global-set-key "\C-c\C-i" 'yas-insert-snippet)
(global-set-key "\C-c\C-p" 'treemacs)
(global-set-key "\C-cp" 'treemacs)
(global-set-key "\C-c\C-tf" 'projectile-find-file)
(global-set-key "\C-c\C-tu" 'flymake-show-buffer-diagnostics)
(global-set-key "\C-c\C-tc" 'treemacs-collapse-all-projects)
(global-set-key "\C-c\C-tg" 'helm-grep-do-git-grep)
(global-unset-key "\M-;")
(global-set-key "\M-;" 'copilot-accept-completion)
(global-set-key (kbd "ESC <down>") 'treemacs-move-project-down)
(global-set-key (kbd "ESC <up>") 'treemacs-move-project-up)
(global-set-key "\C-c\C-o" 'sort-buffers)
