name: Ansible syntax check

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: "3.12"
      - name: Install Ansible Core
        run: python -m pip install ansible-core
      - name: Check playbook syntax
        run: ansible-playbook --syntax-check -i localhost, playbook.yml
