name: Emacs Lisp Format Check

on:
  push:
    branches:
      - "master"

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        # actions/checkout@7.0.1
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Install Emacs
        run: sudo apt-get install -y emacs-nox

      - name: Install pyenv
        # actions/setup-python@7.0.0
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: "3.12.13"

      - name: Install elisp-autofmt into emacs
        run: |
          mkdir -p ~/.emacs.d/elpa/elisp-autofmt-latest/
          wget -O ~/.emacs.d/elpa/elisp-autofmt-latest/elisp-autofmt.el https://codeberg.org/ideasman42/emacs-elisp-autofmt/raw/commit/5ae24d82ee01a849554c4f0f3bfadb007f558693/elisp-autofmt.el

      - name: Run format_elisp_files.sh
        run: sh ./format_elisp_files.sh

      - name: Check diff
        run: git diff --exit-code
