name: Semgrep

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout repository
        # actions/checkout@7.0.1
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Run Semgrep
        run: semgrep --config=auto .
